name: poc-test-learner

description: test a file supplied by user for accuracy

inputs:
  test:
    description: test from the course repo youd like to perform
    required: true
  file:
    description: file to run tests for
    required: true

runs:
  using: "docker"
  image: docker://containers.pkg.github.com/mattdavis0351/actions-poc:latest
  args:
    - ${{inputs.test}}
    - ${{inputs.file}}
