name: poc-test-learner

description: test a file supplied by user for accuracy

inputs:
  test:
    description: test from the course repo youd like to perform
    required: true
  file:
    description: file to run tests for
    required: true
  course-image:
    description: image and tag for the course environment
    required: true

runs:
  using: "docker"
  image: ${{inputs.course-image}}
  args:
    - ${{inputs.test}}
    - ${{inputs.file}}
  entrypoint: "entrypoint.sh" # add to test for reusability.  Add pip install to script.
