name: poc-test-learner

description: test a file supplied by user for accuracy

inputs:
  test:
    description: test from the course repo youd like to perform
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.test}}
