name: 'Github Education Flutter actions'
description: 'Basic Flutter actions to enable rapid development.'

inputs:
  test:
    description: 'Boolean field specifying whether or not Flutter tests should be run.'
    required: true
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test }}
